END_OF_WORLD_DATE = "2036-02-03"
COMPANY_NAME = "PykHub"
COPYRIGHT = "Pykih Software LLP (c) 2013"
POWERED = "<a href='http://www.pykih.com' target='_blank'>Powered by pykih.com</a>"
ENABLE_TINYCON = false
PICTURE_SERVICE_PROVIDER = "GRAVATAR" # or "GRAVATAR or S3"
TELERIVET_API_KEY = '6LM42CZAWCP4A4NEEAWALLN9UT9U4U2C'
TELERIVET_PROJECT_ID = 'PJd04fe057df409528'
TELERIVET_PROJECT_IDPHONE_ID = 'PN6d67f2d05de9c69b'
TELERIVET_WEBHOOK_SECRET = 'AGERFTM2NP9N7GFLGUFRZTFMTCRQADPH'