toolbar1: insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image
plugins:
  - textcolor
  - table
  - image
  - media
  - autolink
  - lists
  - link
  - anchor
  - code
  - code

theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
  - force_hex_style_colors

